### ISSUE TITLE
ECS Tasks fail to start with error: "failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address..." 

### ISSUE THREAD

**Issue by wlokes** [aws/amazon-ecs-cni-plugins#93] opened 2019-06-07 16:33 UTC
### Summary

Many ECS Tasks with EC2 launch type fail to start. The tasks show "STOPPED(Task failed to start)" with no other reason. Eventually, after a dozen or more failed tasks, 1 will start successfully. 

### Description

Cluster contains two `t3.medium` EC2 instances will sufficient memory and CPU to for the tasks. 

The ECS Agent logs repeatedly have this statement with different MAC addresses:
```
2019-06-06T20:59:57Z [INFO] Task engine [arn:aws:ecs:us-west-2:<removed>:task/76de0a43-cfb4-4dac-9348-38c606bd85e3]: error transitioning container [~internal~ecs~pause] to [RESOURCES_PROVISIONED]: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '06:f9:c4:dc:54:70': engine: device with mac address not found
``` 
### Expected Behavior

ECS Tasks to start without error

### Observed Behavior

ECS tasks fail to start. The ECS console displays "STOPPED(Task failed to start)" and the ECS agent logged the above statement
### Environment Details

**docker info**
```
Containers: 10
 Running: 3
 Paused: 0
 Stopped: 7
Images: 57
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 10.07GB
 Data Space Total: 23.33GB
 Data Space Available: 13.26GB
 Metadata Space Used: 5.718MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 19.45MB
 Thin Pool Minimum Free Space: 2.333GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.106-79.86.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.796GiB
Name: ip-172-29-24-116
ID: TMCH:MHDK:PBQU:H6DU:FGVM:SSLZ:ZUFU:K2RR:PMXT:NHNB:Y3DS:YEJC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**curl http://localhost:51678/v1/metadata**
```{"Cluster":"dev","ContainerInstanceArn":"arn:aws:ecs:us-west-2:<removed>:container-instance/4e41dc85-1b37-40d5-b010-0ce35cf0a7a1","Version":"Amazon ECS Agent - v1.28.0 (d2456beb)"}
```
### Supporting Log Snippets

From ECS Agent
```
2019-06-06T20:59:57Z [INFO] Task engine [arn:aws:ecs:us-west-2:<removed>:task/76de0a43-cfb4-4dac-9348-38c606bd85e3]: error transitioning container [~internal~ecs~pause] to [RESOURCES_PROVISIONED]: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '06:f9:c4:dc:54:70': engine: device with mac address not found
```

**Comment by nazar** [comment] 2019-06-13 15:04
We're seeing this as well with the exact same symptoms as described:

>The tasks show "STOPPED(Task failed to start)" with no other reason. Eventually, after a dozen or more failed tasks, 1 will start successfully

We seem to only be able to run one ECS task at a time on our EC2 on a `t2.medium` instance, which uses an Amazon ECS-optimized Amazon Linux 2 AMI 

```
2019-06-13T13:55:59Z [WARN] Managed task [arn:aws:ecs:us-east-1:417483828938:task/0a4563d3-ddc4-44ce-9b46-a0cd0eb1d05f]: error starting/provisioning container[~internal~ecs~pause]; marking its desired status as STOPPED: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:62:5b:0f:db:fa': engine: device with mac address not found
2019-06-13T13:56:35Z [INFO] Task engine [arn:aws:ecs:us-east-1:417483828938:task/aab57f4b-623e-4e7d-9e93-2412a0aa8106]: error transitioning container [~internal~ecs~pause] to [RESOURCES_PROVISIONED]: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:04:b7:45:9a:08': engine: device with mac address not found
2019-06-13T13:56:35Z [WARN] Managed task [arn:aws:ecs:us-east-1:417483828938:task/aab57f4b-623e-4e7d-9e93-2412a0aa8106]: error starting/provisioning container[~internal~ecs~pause]; marking its desired status as STOPPED: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:04:b7:45:9a:08': engine: device with mac address not found
```

```
uname -a
snip ip - 4.14.114-105.126.amzn2.x86_64 #1 SMP Tue May 7 02:26:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Versions:

Agent version:  1.28.1

The above errors seem to coincide with Tasks that are stopped with a `STOPPED(Task failed to start)` status.

docker info

```
Containers: 98
 Running: 1
 Paused: 0
 Stopped: 97
Images: 224
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.114-105.126.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.851GiB
Name: ip-10-242-180-200.ec2.internal
ID: UG6C:6OZX:HHI3:IN6T:CRTL:EABA:P2KT:OIUL:RU4U:C7T3:4DE2:UGOH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Please 🙏 let me know if there is any additional information I can provide.

**Comment by fenxiong** [comment] 2019-06-13 17:33
@wlokes @nazar sorry to hear that you are hitting the issue. The error "cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:04:b7:45:9a:08': engine: device with mac address not found" indicates that the plugin is not able to find the network device on the instance for the ENI after the ENI is attached, which means there's potentially a problem in EC2 networking service or the EC2 instance.

We have been investigating this, but the issue has not been successfully reproduced. Can you tell us a bit more about this so we can narrow done the situation for this issue to happen:
* How many awsvpc tasks have been ran on the instance until you first hit this error? How frequent were the tasks launched? Were they launched with the service scheduler?
* After there was a task failed with this error, does subsequent awsvpc tasks mostly or all fail with this error?
* When this issue happens, if you manually attach an ENI to the instance, is the ENI able to show up on the instance (e.g. show up in the output of "ip link show")?
* Does the EC2 instance that has this issue has ever been rebooted/restarted? If so, did the issue happen after the reboot/restart, or before, or both?
* Do you have a reliable way to reproduce the issue?

Thanks.

**Comment by nazar** [comment] 2019-06-14 12:58
Super thanks for the reply @fenxiong 

>Does the EC2 instance that has this issue has ever been rebooted/restarted?

I don't think we ever rebooted this EC2 instance since we fired up this setup about a week ago. We just rebooted the EC2 instance and I can report that we are no longer seeing this issue and we are now seeing two ECS tasks running on the EC2 instance (as expected)

We also updated the ecs-agent to `1.29.0` and I'm super embarrassed to say that I'm not sure whether the reboot or the agent update addressed the issue. 

We've never been able to start more than one ECS agent on this EC2 instance. I just ran a couple more ECS tasks and they continue to start as expected.

🤞 this is no longer an issue for us 🤞

Again, thank you @fenxiong  for checking.

**Comment by nazar** [comment] 2019-07-17 18:09
We've started seeing this again @fenxiong where most ECS tasks on the EC2 cluster fail to start with nothing being output to cloudWatch and ECS task details page for a failed task have no information as to why.

![Screen Shot 2019-07-17 at 19 06 29](https://user-images.githubusercontent.com/6967/61399402-03aa6380-a8c6-11e9-9c4b-510a2a8b2fe1.png)

>How many awsvpc tasks have been ran on the instance until you first hit this error? 

Several (maybe in the hundreds) but we have no way of knowing exact numbers as this is an EC2 ECS Cluster instance. I would say about less than 10% of tasks start successfully on on this EC2 ECS Cluster

![Screen Shot 2019-07-17 at 18 39 58](https://user-images.githubusercontent.com/6967/61399293-baf2aa80-a8c5-11e9-9ece-a6c3497ddbe1.png)

>How frequent were the tasks launched?

When tasks are failing new ECS tasks are re-started within a minute or less. The timing is outside our control as this EC2 ECS Cluster instance is a Jenkins slave and ECS `jenkins/jnlp-slave` based tasks are launched on it via the [Amazon Elastic Container Service plugin](https://wiki.jenkins-ci.org/display/JENKINS/Amazon+EC2+Container+Service+Plugin) from another EC2 ECS cluster.

>Were they launched with the service scheduler?

No - launched via [Amazon Elastic Container Service plugin](https://wiki.jenkins-ci.org/display/JENKINS/Amazon+EC2+Container+Service+Plugin) with a success launch rate of under 10%

>After there was a task failed with this error, does subsequent awsvpc tasks mostly or all fail with this error?

Subsequent tasks mostly fail after this error but some don't (small percentage)

>When this issue happens, if you manually attach an ENI to the instance, is the ENI able to show up on the instance (e.g. show up in the output of "ip link show")?

Sorry but don't know how to do or answer this but `ip link show` outputs:

```
[root@ip-10-242-180-200 ec2-user]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 02:06:9d:f1:6b:34 brd ff:ff:ff:ff:ff:ff
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:ef:d0:3d:44 brd ff:ff:ff:ff:ff:ff
7: ecs-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether fa:ad:1f:4d:54:1d brd ff:ff:ff:ff:ff:ff
2060: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 02:d7:bd:c9:b5:ce brd ff:ff:ff:ff:ff:ff
4293: veth76ba2a25@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ecs-bridge state UP mode DEFAULT group default
    link/ether fa:ad:1f:4d:54:1d brd ff:ff:ff:ff:ff:ff link-netnsid 0
4294: br-59ee6881b345: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:8c:07:ab:ab brd ff:ff:ff:ff:ff:ff
4306: veth99dbdc5@if4305: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-59ee6881b345 state UP mode DEFAULT group default
    link/ether e6:f4:a8:a6:48:ea brd ff:ff:ff:ff:ff:ff link-netnsid 1
4310: veth5937267@if4309: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-59ee6881b345 state UP mode DEFAULT group default
    link/ether e2:59:e2:8a:80:df brd ff:ff:ff:ff:ff:ff link-netnsid 3
4312: vetha57d25c@if4311: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-59ee6881b345 state UP mode DEFAULT group default
    link/ether 82:f7:ca:dd:a2:c7 brd ff:ff:ff:ff:ff:ff link-netnsid 4
4314: vethd88c826@if4313: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-59ee6881b345 state UP mode DEFAULT group default
    link/ether 8a:75:4c:bc:9a:77 brd ff:ff:ff:ff:ff:ff link-netnsid 5
```

>Does the EC2 instance that has this issue has ever been rebooted/restarted? If so, did the issue happen after the reboot/restart, or before, or both?

We initially thought that a reboot fixed this but these issues soon return after subsequent reboots.

>Do you have a reliable way to reproduce the issue?

This can be consistently observed on EC2 instanceId `i-006e92746ed1b93eb`

Here is a snippet of the /var/log/ecs/ecs-agent.log file

```
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: unable to create state change event for container [~internal~ecs~pause]: create container state change event api: status not recognized by ECS: RUNNING
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: task not steady state or terminal; progressing it
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: waiting for event for task
2019-07-17T17:38:49Z [INFO] Task engine [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: setting up container resources for container [~internal~ecs~pause]
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: got container [~internal~ecs~pause] event: [RUNNING]
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: handling container change [{RUNNING {16d7bb8c7e27aa39e32dc28a8a1c406f2c4d9f41d4a1d8f0df6cde720f078761 <nil> [] <nil> [] map[com.amazonaws.ecs.cluster:aa-jenkins-ci-slaves com.amazonaws.ecs.container-name:~internal~ecs~pause com.amazonaws.ecs.task-arn:arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab com.amazonaws.ecs.task-definition-family:aa-jenkins-ci-slaves-template com.amazonaws.ecs.task-definition-version:15] 2019-07-17 17:38:49.299878888 +0000 UTC 2019-07-17 17:38:49.621743072 +0000 UTC 0001-01-01 00:00:00 +0000 UTC {UNKNOWN <nil> 0 } none 0xc000904b00} ContainerStatusChangeEvent}] for container [~internal~ecs~pause]
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: redundant container state change. ~internal~ecs~pause to RUNNING, but already RUNNING
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: task not steady state or terminal; progressing it
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: waiting for event for task
2019-07-17T17:38:49Z [ERROR] Task engine [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: unable to configure pause container namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:12:48:fd:58:d4': engine: device with mac address not found
2019-07-17T17:38:49Z [INFO] Task engine [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: error transitioning container [~internal~ecs~pause] to [RESOURCES_PROVISIONED]: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:12:48:fd:58:d4': engine: device with mac address not found
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: got container [~internal~ecs~pause] event: [RESOURCES_PROVISIONED]
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: handling container change [{RESOURCES_PROVISIONED {16d7bb8c7e27aa39e32dc28a8a1c406f2c4d9f41d4a1d8f0df6cde720f078761 <nil> [] container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:12:48:fd:58:d4': engine: device with mac address not found [] map[] 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC {UNKNOWN <nil> 0 }  <nil>} ContainerStatusChangeEvent}] for container [~internal~ecs~pause]
2019-07-17T17:38:49Z [WARN] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: error starting/provisioning container[~internal~ecs~pause]; marking its desired status as STOPPED: container resource provisioning: failed to setup network namespace: cni setup: invoke eni plugin failed: getInterfaceDeviceName engine: unable to get device with hardware address '02:12:48:fd:58:d4': engine: device with mac address not found
2019-07-17T17:38:49Z [INFO] api/task: Updating task desired status to stopped because of container: [~internal~ecs~pause]; task: [aa-jenkins-ci-slaves-template:15 arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab, TaskStatus: (NONE->RUNNING) Containers: [aa-jenkins-ci-slaves-template (NONE->RUNNING),~internal~ecs~pause (RUNNING->STOPPED), ENI: [eni id:eni-0dc7367b6c9c66595, mac: 02:12:48:fd:58:d4, hostname: ip-10-242-180-137.ec2.internal, ipv4addresses: [10.242.180.137], ipv6addresses: [], dns: [], dns search: [], gateway ipv4: [10.242.180.1/24][ ,VLan ID: [], TrunkInterfaceMacAddress: []]]]]
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: task not steady state or terminal; progressing it
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: waiting for event for task
2019-07-17T17:38:49Z [INFO] Task engine [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: stopping container [~internal~ecs~pause]
2019-07-17T17:38:49Z [INFO] Task engine [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: cleaning up the network namespace
2019-07-17T17:38:49Z [INFO] Managed task [arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab]: got resource [cgroup] event: [REMOVED]
2019-07-17T17:38:49Z [INFO] api/task: Updating task desired status to stopped because of container: [aa-jenkins-ci-slaves-template]; task: [aa-jenkins-ci-slaves-template:15 arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab, TaskStatus: (NONE->STOPPED) Containers: [aa-jenkins-ci-slaves-template (NONE->STOPPED),~internal~ecs~pause (RUNNING->STOPPED), ENI: [eni id:eni-0dc7367b6c9c66595, mac: 02:12:48:fd:58:d4, hostname: ip-10-242-180-137.ec2.internal, ipv4addresses: [10.242.180.137], ipv6addresses: [], dns: [], dns search: [], gateway ipv4: [10.242.180.1/24][ ,VLan ID: [], TrunkInterfaceMacAddress: []]]]]
2019-07-17T17:38:49Z [INFO] api/task: Updating task desired status to stopped because of container: [~internal~ecs~pause]; task: [aa-jenkins-ci-slaves-template:15 arn:aws:ecs:us-east-1:417483828938:task/d4961270-ad95-443a-ba54-454a8f025eab, TaskStatus: (NONE->STOPPED) Containers: [aa-jenkins-ci-slaves-template (NONE->STOPPED),~internal~ecs~pause (RUNNING->STOPPED), ENI: [eni id:eni-0dc7367b6c9c66595, mac: 02:12:48:fd:58:d4, hostname: ip-10-242-180-137.ec2.internal, ipv4addresses: [10.242.180.137], ipv6addresses: [], dns: [], dns search: [], gateway ipv4: [10.242.180.1/24][ ,VLan ID: [], TrunkInterfaceMacAddress: []]]]]
```

Latest snippets from `/var/log/ecs/ecs-cni-eni-plugin.log`:

```
2019-07-17T17:41:30Z [ERROR] Unable to find network device for ENI (mac address=02:41:ba:59:ea:78): getInterfaceDeviceName engine: unable to get device with hardware address '02:41:ba:59:ea:78': engine: device with mac address not found
2019-07-17T17:42:02Z [ERROR] Unable to find network device for ENI (mac address=02:81:e4:31:b6:28): getInterfaceDeviceName engine: unable to get device with hardware address '02:81:e4:31:b6:28': engine: device with mac address not found
2019-07-17T17:42:38Z [ERROR] Unable to find network device for ENI (mac address=02:26:00:ff:69:74): getInterfaceDeviceName engine: unable to get device with hardware address '02:26:00:ff:69:74': engine: device with mac address not found
2019-07-17T17:43:08Z [ERROR] Unable to find network device for ENI (mac address=02:ba:fc:1f:70:d4): getInterfaceDeviceName engine: unable to get device with hardware address '02:ba:fc:1f:70:d4': engine: device with mac address not found
2019-07-17T17:43:34Z [ERROR] Unable to find network device for ENI (mac address=02:a0:3b:24:76:e0): getInterfaceDeviceName engine: unable to get device with hardware address '02:a0:3b:24:76:e0': engine: device with mac address not found
2019-07-17T17:44:15Z [ERROR] Unable to find network device for ENI (mac address=02:7d:37:84:54:f4): getInterfaceDeviceName engine: unable to get device with hardware address '02:7d:37:84:54:f4': engine: device with mac address not found
2019-07-17T17:44:49Z [ERROR] Unable to find network device for ENI (mac address=02:5b:df:81:b7:c2): getInterfaceDeviceName engine: unable to get device with hardware address '02:5b:df:81:b7:c2': engine: device with mac address not found
2019-07-17T17:45:29Z [ERROR] Unable to find network device for ENI (mac address=02:60:a4:2e:6f:b4): getInterfaceDeviceName engine: unable to get device with hardware address '02:60:a4:2e:6f:b4': engine: device with mac address not found
2019-07-17T17:45:59Z [ERROR] Unable to find network device for ENI (mac address=02:97:8d:e8:a5:5e): getInterfaceDeviceName engine: unable to get device with hardware address '02:97:8d:e8:a5:5e': engine: device with mac address not found
2019-07-17T17:46:34Z [ERROR] Unable to find network device for ENI (mac address=02:02:46:5e:ec:2a): getInterfaceDeviceName engine: unable to get device with hardware address '02:02:46:5e:ec:2a': engine: device with mac address not found
2019-07-17T17:46:54Z [INFO] Found network device for the ENI (mac address=02:44:a9:61:15:76): eth2
2019-07-17T17:46:54Z [INFO] Read ipv4 gateway and netmask from config for ENI (device name=eth2): 10.242.180.1 24
2019-07-17T17:46:54Z [INFO] ENI 02:44:a9:61:15:76 (device name=eth2) has been assigned to the container's namespace
2019-07-17T17:47:15Z [ERROR] Unable to find network device for ENI (mac address=02:82:11:ee:19:3e): getInterfaceDeviceName engine: unable to get device with hardware address '02:82:11:ee:19:3e': engine: device with mac address not found
2019-07-17T17:48:05Z [ERROR] Unable to find network device for ENI (mac address=02:b1:03:ca:32:60): getInterfaceDeviceName engine: unable to get device with hardware address '02:b1:03:ca:32:60': engine: device with mac address not found
2019-07-17T17:48:28Z [INFO] Found network device for the ENI (mac address=02:6c:88:90:79:aa): eth2
2019-07-17T17:48:28Z [INFO] Read ipv4 gateway and netmask from config for ENI (device name=eth2): 10.242.180.1 24
2019-07-17T17:48:28Z [INFO] ENI 02:6c:88:90:79:aa (device name=eth2) has been assigned to the container's namespace
2019-07-17T17:48:51Z [ERROR] Unable to find network device for ENI (mac address=02:73:c7:16:cc:5e): getInterfaceDeviceName engine: unable to get device with hardware address '02:73:c7:16:cc:5e': engine: device with mac address not found
2019-07-17T17:49:40Z [ERROR] Unable to find network device for ENI (mac address=02:a6:c8:05:0e:7e): getInterfaceDeviceName engine: unable to get device with hardware address '02:a6:c8:05:0e:7e': engine: device with mac address not found
2019-07-17T17:50:29Z [ERROR] Unable to find network device for ENI (mac address=02:79:83:ce:d3:94): getInterfaceDeviceName engine: unable to get device with hardware address '02:79:83:ce:d3:94': engine: device with mac address not found
2019-07-17T17:51:23Z [ERROR] Unable to find network device for ENI (mac address=02:8f:59:98:14:90): getInterfaceDeviceName engine: unable to get device with hardware address '02:8f:59:98:14:90': engine: device with mac address not found
2019-07-17T17:52:09Z [ERROR] Unable to find network device for ENI (mac address=02:df:49:cf:01:36): getInterfaceDeviceName engine: unable to get device with hardware address '02:df:49:cf:01:36': engine: device with mac address not found
2019-07-17T17:53:01Z [ERROR] Unable to find network device for ENI (mac address=02:c4:fb:b3:2c:c2): getInterfaceDeviceName engine: unable to get device with hardware address '02:c4:fb:b3:2c:c2': engine: device with mac address not found
2019-07-17T17:53:49Z [ERROR] Unable to find network device for ENI (mac address=02:1d:2e:15:1e:12): getInterfaceDeviceName engine: unable to get device with hardware address '02:1d:2e:15:1e:12': engine: device with mac address not found
2019-07-17T17:54:41Z [ERROR] Unable to find network device for ENI (mac address=02:13:29:41:a3:a2): getInterfaceDeviceName engine: unable to get device with hardware address '02:13:29:41:a3:a2': engine: device with mac address not found
2019-07-17T17:55:30Z [ERROR] Unable to find network device for ENI (mac address=02:02:f7:e6:50:46): getInterfaceDeviceName engine: unable to get device with hardware address '02:02:f7:e6:50:46': engine: device with mac address not found
2019-07-17T17:56:19Z [ERROR] Unable to find network device for ENI (mac address=02:6c:74:f5:c2:08): getInterfaceDeviceName engine: unable to get device with hardware address '02:6c:74:f5:c2:08': engine: device with mac address not found
2019-07-17T17:57:09Z [ERROR] Unable to find network device for ENI (mac address=02:f5:e1:30:78:9c): getInterfaceDeviceName engine: unable to get device with hardware address '02:f5:e1:30:78:9c': engine: device with mac address not found
2019-07-17T17:58:09Z [ERROR] Unable to find network device for ENI (mac address=02:b9:97:f1:08:4c): getInterfaceDeviceName engine: unable to get device with hardware address '02:b9:97:f1:08:4c': engine: device with mac address not found
2019-07-17T17:58:38Z [ERROR] Unable to find network device for ENI (mac address=02:3f:9d:2e:e4:f2): getInterfaceDeviceName engine: unable to get device with hardware address '02:3f:9d:2e:e4:f2': engine: device with mac address not found
2019-07-17T17:59:01Z [ERROR] Unable to find network device for ENI (mac address=02:77:bf:6e:75:be): getInterfaceDeviceName engine: unable to get device with hardware address '02:77:bf:6e:75:be': engine: device with mac address not found
```

**Comment by FLavalliere** [comment] 2019-09-06 03:17
Not sure if it may help?  I had a VM where i tried to enable awsvpctrunk (not yet recreted it.)


```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbb32fd]

goroutine 209 [running]:
github.com/aws/amazon-ecs-agent/agent/api/eni.(*ENIAttachment).StopAckTimer(0xc000400ab0)
        /go/src/github.com/aws/amazon-ecs-agent/agent/api/eni/eniattachment.go:99 +0x6d
github.com/aws/amazon-ecs-agent/agent/eventhandler.setTaskAttachmentSent(0xc0005184b0)
        /go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler_types.go:217 +0x50
github.com/aws/amazon-ecs-agent/agent/eventhandler.(*sendableEvent).send(0xc0005184b0, 0x1246f80, 0x1246f90, 0x120f935, 0xf, 0x14156a0, 0xc0003e25a0, 0xc00051d4d0, 0x7fdf6b97c0a0, 0xc0003020e0, ...)
        /go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler_types.go:161 +0x30e
github.com/aws/amazon-ecs-agent/agent/eventhandler.(*taskSendableEvents).submitFirstEvent(0xc0005b3880, 0xc000299050, 0x1402860, 0xc000256bd0, 0x0, 0x0, 0x0)
        /go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:368 +0x58f
github.com/aws/amazon-ecs-agent/agent/eventhandler.(*TaskHandler).submitTaskEvents.func1(0x0, 0x0)
        /go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:295 +0x10f
github.com/aws/amazon-ecs-agent/agent/utils/retry.RetryWithBackoffCtx(0x140e8a0, 0xc000044018, 0x1402860, 0xc000256bd0, 0xc00051d530, 0x1248e38, 0x0)
        /go/src/github.com/aws/amazon-ecs-agent/agent/utils/retry/retry.go:46 +0x85
github.com/aws/amazon-ecs-agent/agent/utils/retry.RetryWithBackoff(...)
        /go/src/github.com/aws/amazon-ecs-agent/agent/utils/retry/retry.go:29
github.com/aws/amazon-ecs-agent/agent/eventhandler.(*TaskHandler).submitTaskEvents(0xc000299050, 0xc0005b3880, 0x14156a0, 0xc0003e25a0, 0xc0003c1b60, 0x57)
        /go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:287 +0x147
created by github.com/aws/amazon-ecs-agent/agent/eventhandler.(*taskSendableEvents).sendChange
        /go/src/github.com/aws/amazon-ecs-agent/agent/eventhandler/task_handler.go:326 +0x24f
```

**Comment by daniel1302** [comment] 2019-09-17 10:25
Hi I have similar issue, described here:

https://stackoverflow.com/questions/57944911/the-ecs-servive-with-aws-vpc-cannot-start-due-to-eni-issues

**Comment by fenxiong** [comment] 2019-09-17 16:03
@daniel1302 your issue is a different issue, described in summary of https://github.com/aws/amazon-ecs-agent/pull/2085 and fixed by that. Agent version 1.28.1 and 1.29.0 have this issue, and it's fixed starting from 1.29.1. If you upgrade the agent to the latest version this issue should not appear anymore (note that if your instance already has the issue, you need to launch a new instance with latest agent rather than replacing the agent on the original instance).

**Comment by fenxiong** [comment] 2019-09-17 17:44
@nazar sorry for the late response. there had been an issue related to ENI attaching which might have caused the error you have, but it should be fixed by now. are you still seeing this issue (even on instances that are launched recently)?

**Comment by nazar** [comment] 2019-09-17 18:05
Hey @fenxiong - thank you for the follow up 🙏 

We're not seeing this anymore after we bumped our number of EC2 instances to two `c5d.large` in the ECS cluster about a month (give or take a week) or so ago? I'm happy 😄 this is no longer an issue - thank you. 

Very sorry I didn't update the ticket back then.

**Comment by daniel1302** [comment] 2019-09-17 19:53
I also had a similar issue with 2 instances(small but still):
https://stackoverflow.com/questions/57944911/the-ecs-servive-with-aws-vpc-cannot-start-due-to-eni-issues

**Comment by mssrivas** [comment] 2020-10-15 00:08
@daniel1302 thank you for commenting. Were you able to solve this by bumping the agent version?

**Comment by mssrivas** [comment] 2021-08-24 23:02
closing this as no response has been received.

**Closed by mssrivas** 2021-08-24 23:02 UTC
